### ISSUE TITLE
SND - > DNS

### ISSUE THREAD

**Issue by ErikThorsell** [dtekcth/dns#1]
There is no longer an SND association.

**Comment by Hagesjo** [comment]
Ahh, true

Is fix.

On 4 December 2015 at 12:31, Erik Thorsell notifications@github.com wrote:

> There is no longer an SND association.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dtekcth/snd/issues/1.

## 

Andreas "Ankaan" Hagesjö
Kassör NitroXy
0768475112
andreas.hagesjo@nitroxy.com
